export const myProjectColumns = [{
        title: "项目名称",
        dataIndex: "projectName",
        key: "projectName",
        align: "center",
        width: 120,
    },
    {
        title: "国家代码",
        dataIndex: "countryCode",
        key: "countryCode",
        align: "center",
        width: 120,
    },
    {
        title: "建设单位",
        dataIndex: "constructionUnit",
        key: "constructionUnit",
        align: "center",
        width: 120,
    },
    {
        title: "项目总投资（万元）",
        dataIndex: "totalInvestment",
        key: "totalInvestment",
        align: "center",
        width: 120,
    },
    {
        title: "资金来源",
        dataIndex: "fundingSource",
        key: "fundingSource",
        align: "center",
        width: 120,
    },
    {
        title: "是否发改立项",
        dataIndex: "isNDRCApproved",
        key: "isNDRCApproved",
        align: "center",
        width: 120,
    },
    {
        title: "立项批复号",
        dataIndex: "approvalNumber",
        key: "approvalNumber",
        align: "center",
        width: 120,
    },
    {
        title: "批复类型",
        dataIndex: "approvalType",
        key: "approvalType",
        align: "center",
        width: 120,
    },
    {
        title: "项目类型",
        dataIndex: "projectType",
        key: "projectType",
        align: "center",
        width: 120,
    },
    {
        title: "实施建设单位",
        dataIndex: "implementingUnit",
        key: "implementingUnit",
        align: "center",
        width: 120,
    },
    {
        title: "合同信息（评审）",
        dataIndex: "contractInfo",
        key: "contractInfo",
        align: "center",
        width: 120,
    },
    {
        title: "合同支付信息",
        dataIndex: "contractPaymentInfo",
        key: "contractPaymentInfo",
        align: "center",
        width: 120,
    },
    {
        title: "项目状态",
        dataIndex: "projectStatus",
        key: "projectStatus",
        align: "center",
        width: 120,
    },
    {
        title: "历史结算次数",
        dataIndex: "settlementCount",
        key: "settlementCount",
        align: "center",
        width: 120,
    },
    {
        title: "历史结算总审金额（元）",
        dataIndex: "totalSettlementAmount",
        key: "totalSettlementAmount",
        align: "center",
        width: 120,
    },
    {
        title: "历史结算总审定金额（元）",
        dataIndex: "totalSettlementApprovedAmount",
        key: "totalSettlementApprovedAmount",
        align: "center",
        width: 120,
    },
    {
        title: "历史结算总核减金额（元）",
        dataIndex: "totalSettlementReductionAmount",
        key: "totalSettlementReductionAmount",
        align: "center",
        width: 120,
    },
    {
        title: "平均核减率",
        dataIndex: "averageReductionRate",
        key: "averageReductionRate",
        align: "center",
        width: 120,
    },
    {
        title: "开始结算评审时间",
        dataIndex: "settlementReviewStartTime",
        key: "settlementReviewStartTime",
        align: "center",
        width: 120,
    },
    {
        title: "最近一次结算办结时间",
        dataIndex: "latestSettlementCompletionTime",
        key: "latestSettlementCompletionTime",
        align: "center",
        width: 120,
    },
    {
        title: "最近一份结算报告号",
        dataIndex: "latestSettlementReportNumber",
        key: "latestSettlementReportNumber",
        align: "center",
        width: 120,
    },
    {
        title: "第一份结算报告号",
        dataIndex: "firstSettlementReportNumber",
        key: "firstSettlementReportNumber",
        align: "center",
        width: 120,
    },
    {
        title: "是否超概算",
        dataIndex: "isExceedingBudget",
        key: "isExceedingBudget",
        align: "center",
        width: 120,
    },
    {
        title: "决算报告号",
        dataIndex: "finalAccountReportNumber",
        key: "finalAccountReportNumber",
        align: "center",
        width: 120,
    },
    {
        title: "项目开工时间",
        dataIndex: "projectStartDate",
        key: "projectStartDate",
        align: "center",
        width: 120,
    },
    {
        title: "项目竣工时间",
        dataIndex: "projectCompletionDate",
        key: "projectCompletionDate",
        align: "center",
        width: 120,
    },
    {
        title: "与支付合同对接",
        dataIndex: "paymentContractIntegration",
        key: "paymentContractIntegration",
        align: "center",
        width: 120,
    },
    {
        title: "操作",
        dataIndex: "actions",
        key: "actions",
        align: "center",
        width: 150,
        fixed: 'right'
    },
];